name: Playwright Tests

on:

  schedule:
    - cron: '30 22 * * *'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: ./.github/actions/pnpm-setup-node

      - name: Install package
        run: pnpm install --frozen-lockfile

      - name: Install package
        run: pnpm install cross-env

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests
        id: playwright
        run: |
          pnpm dev ./carbon-track/smoke-test > test_results.txt
          echo "::set-output name=test_output::$(cat test_results.txt)"
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          TEST_RESULTS: ${{ steps.playwright.outputs.test_output }}
        run: |
          result_emoji=$([ "${{ job.status }}" == "success" ] && echo ":white_check_mark:" || echo ":x:")
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"${result_emoji} Playwright Test for *${GITHUB_WORKFLOW}* completed with status: ${{ job.status }}\n\nTest Results:\n${TEST_RESULTS}\"}" \
          $SLACK_WEBHOOK