name: Playwright Tests

on:
  schedule:
    - cron: '30 22 * * *'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: ./.github/actions/pnpm-setup-node

       - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-  

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests and generate summary
        run: |
          pnpm playwright test ./tests/naver --reporter=list,html > test_output.txt
          echo "TEST_SUMMARY<<EOF" >> $GITHUB_ENV
          tail -n 20 test_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
        run: |
          result_emoji=$([ "${{ job.status }}" == "success" ] && echo ":white_check_mark:" || echo ":x:")
          artifact_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          summary="${{ env.TEST_SUMMARY }}"
          
          # Escape special characters for JSON
          summary=$(echo "$summary" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"${result_emoji} Playwright Test for *${GITHUB_WORKFLOW}* completed with status: ${{ job.status }}\n\nTest Summary:\n\`\`\`\n${summary}\n\`\`\`\n\nFull report available at: ${artifact_url}\"}" \
          $SLACK_WEBHOOK